name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: "22"
        script: |
          npm i ts-node -g
          cd /root/kv--discord-bot
          pm2 delete kvbot
          git pull
          npm install
          pm2 start "npm run start" --name kvbot
